---
title: "SRF-2018-Code"
author: "Keane Flynn & Weston Slaughter"
date: "12/30/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Load Libraries
```{r}
library(dplyr)
library(readr)
library(tidyverse)
library(ggplot2)
```

#ChlA Data
```{r}
ChlA_Data_Porter <- 
  readr::read_csv(file = "ChlA-Data/ChlA-Data.csv",
                  col_types = "ccccdcddddddddc") %>%
  filter(Site == "Porter_Above") %>%
  group_by(Date_collected, Site_1)
ChlA_Data_Porter
```

##Summarized ChlA Data
```{r}
Summarized_ChlA_Data <- ChlA_Data_Porter %>%
  group_by(Date_collected, Site_1) %>%
  summarise(mean_ChlA_area = mean(Chla_area))
Summarized_ChlA_Data
```

##Plotting ChlA vs Time
```{r}
ChlA_Graph <- Summarized_ChlA_Data %>%
  ggplot(aes(x = Date_collected, y = mean_ChlA_area)) +
  geom_line(aes(group = Site_1, color = Site_1)) +
  geom_point(aes(shape = Site_1)) +
  labs(x = "Date", y = "Average Chlorophyll-A Reading per Unit Area of Cobble") +
  ggtitle("Chlorophyll-A Measurements vs Time")
ChlA_Graph
```

#AFD Data
```{r}
AFD_Data_Porter <-
  readr::read_csv(file = "ChlA-Data/AFD-Data.csv",
                  col_types = "ccccdcddddddddc") %>%
  filter(Site == "Porter_Above") %>%
  group_by(Date_collected, Site_1) %>%
  select(Date_collected, Site_1, Cobble_SID, Pool_or_Riffle, Dry_Weight_g, AFD_Weight_g, Difference)
AFD_Data_Porter
```

##Summarizing AFD Data
```{r}
Summarized_AFD_Data <- AFD_Data_Porter %>%
  filter(!AFD_Weight_g == "NA") %>%
  group_by(Date_collected, Site_1) %>%
  summarise(mean_diff = mean(Difference))
Summarized_AFD_Data
```

##Plotting AFD vs Time
```{r}
AFD_Graph <- Summarized_AFD_Data %>%
  ggplot(aes(x = Date_collected, y = mean_diff)) +
  geom_line(aes(group = Site_1, color = Site_1)) +
  geom_point(aes(shape = Site_1)) +
  labs(x = "Date", y = "Average Chlorophyll Mass Collected per Cobble") +
  ggtitle("Ash Free Dry Mass Measurements vs Time")
AFD_Graph
```

#Dissolved Oxygen Data
```{r}

```
